In [35]:
import pandas as pd
import numpy as np

# Q1. Pandas version

In [2]:
pd.__version__

'3.0.6'

# Getting the data

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')

In [4]:
df.head(5)

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

# Q2. Records count

In [5]:
df.describe().round(2)

,model_year,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
count,10000.00,10000.00,10000.00,10000.00,9123.00,10000.00,9736.00,10000.00
mean,1999.55,3.50,2268.81,6.04,254.45,4286.75,18.89,30.00
std,14.21,0.95,183.45,0.54,22.84,266.21,1.28,2.93
min,1975.00,2.00,1590.00,4.00,171.00,3320.00,14.00,19.80
25%,1987.00,3.00,2150.00,6.00,239.00,4110.00,18.00,28.00
50%,2000.00,4.00,2270.00,6.00,254.00,4280.00,18.90,30.00
75%,2012.00,4.00,2390.00,6.00,270.00,4470.00,19.70,31.90
max,2024.00,5.00,3110.00,8.00,334.00,5460.00,23.80,41.20

# Q3. Fuel types

In [6]:
df.fuel_type.unique()

<StringArray>
['Gasoline', 'Diesel', 'Hybrid']
Length: 3, dtype: str

# Q4. Missing values

In [7]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

# Q5. Max fuel efficiency

In [8]:
df.groupby('origin').fuel_efficiency_mpg.max()

origin
Asia      41.2
Europe    39.4
USA       38.2
Name: fuel_efficiency_mpg, dtype: float64

# Q6. Median value of horsepower

## 1. Find the median value of the horsepower column in the dataset.

In [9]:
print( df.horsepower.mean().round(2) )

254.45

## 2. Next, calculate the most frequent value of the same horsepower column.

In [10]:
print ( df.horsepower.mode() )

0    252.0
Name: horsepower, dtype: float64

## 3. Use the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step.

In [21]:
df_mode = df.copy()
df_mode['horsepower'] = df_mode.horsepower.fillna( df_mode.horsepower.mode()[0] )

## 4. Now, calculate the median value of horsepower once again.

In [22]:
print( df_mode.horsepower.mean().round(2) )

254.23

# Q7. Sum of weights

## 1. Select all the cars from Asia

In [46]:
df_asia = df.copy()
df_asia = df_asia[ df_asia['origin'] == 'Asia']
df_asia.head(5)

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,NaN,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4

## 2. Select only columns vehicle_weight and model_year

In [47]:
df_asia = df_asia [ ['vehicle_weight', 'model_year'] ]
df_asia.head(5)

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007

## 3. Select the first 7 values

In [48]:
df_asia = df_asia.head(7)
df_asia

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

## 4. Get the underlying NumPy array. Let's call it X.

In [49]:
X = df_asia.values
print (X)

[[4240 1996]
 [4310 1992]
 [4230 1997]
 [4420 1978]
 [3950 2007]
 [4750 2021]
 [4450 2019]]

## 5. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.

In [37]:
XTX = X.T.dot(X)
print (XTX)

[[131950500  60750580]
 [ 60750580  28041424]]

## 6. Invert XTX.

In [41]:
XTX_inv = np.linalg.inv(XTX)
print( XTX_inv.dot(XTX).round(2) )

[[ 1. -0.]
 [-0.  1.]]

## 7. Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].

In [42]:
y = [1100, 1300, 800, 900, 1000, 1100, 1200]

## 8. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

In [44]:
w = (XTX_inv.dot(X.T)).dot(y)
print(w)

[0.13644777 0.2327492 ]

## 9. What's the sum of all the elements of the result?

In [45]:
print (w.sum().round(3))

0.369